name: Lastest Hashnode Blog Post
on:
  schedule:
    # Runs once a day
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest Hashnode blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "HASHNODE"
          commit_message: "Updated readme with the latest dev.to Blog data"
          feed_list: "https://dev.to/feed/nicm42"
